name: 2. After PR Processed
# This workflow is triggered by the completion of the primary pull request processing workflow.
# It distinguishes between success and failure of the triggering workflow.
# It is used to set labels and reviewers on the pull request.
on:
  workflow_run:
    workflows: [1_on_pull_request.yml]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

