name: 3A. Approved Pull Request

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true

jobs:
  process_approved_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sandbox-wp-db
        uses: actions/checkout@v4
        with:
          repository: wikipathways/sandbox-wp-db
          path: sandbox-wp-db

      - name: Checkout sandbox-wp.gh.io
        uses: actions/checkout@v4
        with:
          repository: wikipathways/sandbox-wp.gh.io
          path: sandbox-wp.gh.io
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout sandbox-wp-assets
        uses: actions/checkout@v4
        with:
          repository: wikipathways/sandbox-wp-assets
          path: sandbox-wp-assets
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get WPID
        id: get_wpid
        working-directory: sandbox-wp.gh.io
        run: |
          PR_NUMBER=${{ github.event.inputs.pr_number }}
          DRAFT_FILE=$(find _drafts -name "WP*__PR${PR_NUMBER}.md" | head -n 1)
          
          if [ -n "$DRAFT_FILE" ]; then
            WPID_NUM=$(echo $DRAFT_FILE | sed -E 's/WP([0-9]+)__PR.*/\1/')
            if [ "$WPID_NUM" -eq "0" ]; then
              WPID=$(ls _pathways/ | grep -E '^WP[0-9]+\.md$' | sort -V | tail -n 1)
              WPID=$(echo $WPID | sed 's/\.md//')
              WPID_NEW=$(echo $WPID | sed 's/WP//')
              WPID_NEW=$((WPID_NEW + 1))
            else
              WPID_NEW=$((WPID_NUM))
            fi
          else
            echo "No draft file found for PR #${PR_NUMBER}"
            exit 1
          fi
          
          WPID="WP${WPID_NEW}"
          echo "::set-output name=wpid::$WPID"
          echo "::set-output name=old_prefix::WP${WPID_NUM}__PR${PR_NUMBER}"

      - name: Rename and Move Files
        working-directory: sandbox-wp.gh.io
        run: |
          OLD_PREFIX=${{ steps.get_wpid.outputs.old_prefix }}
          WPID=${{ steps.get_wpid.outputs.wpid }}
          
          # Process .md files
          find _drafts -type f -name "${OLD_PREFIX}.md" | while read file; do
            new_file=$(echo $file | sed "s/${OLD_PREFIX}/${WPID}/")
            new_file=$(basename $new_file)
            mkdir -p "../sandbox-wp-db/pathways/${WPID}"
            cp "$file" "../sandbox-wp-db/pathways/${WPID}/${new_file}"
            mv "$file" "_pathways/${new_file}"
          done

          # Process .tsv files
          find _data/drafts -type f -name "${OLD_PREFIX}*.tsv" | while read file; do
            new_file=$(echo $file | sed "s/${OLD_PREFIX}/${WPID}/")
            new_file=$(basename $new_file)
            mv "$file" "_data/${new_file}"
          done

          # Process files in draft_assets
          find draft_assets -type f -name "${OLD_PREFIX}*" | while read file; do
            new_file=$(echo $file | sed "s/${OLD_PREFIX}/${WPID}/")
            new_file=$(basename $new_file)
            #Skip SVG files
            if [[ $file != *.svg ]]; then
              cp "$file" "../sandbox-wp-db/pathways/${WPID}/${new_file}"
            fi
            mkdir -p "../sandbox-wp-assets/pathways/${WPID}"
            mv "$file" "../sandbox-wp-assets/pathways/${WPID}/${new_file}"
          done

      - name: Commit and push changes to sandbox-wp.gh.io
        working-directory: sandbox-wp.gh.io
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Publish approved pathway WP${{ steps.get_wpid.outputs.wpid }}"
          git push

      - name: Commit and push changes to sandbox-wp-db
        working-directory: sandbox-wp-db
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add files for approved pathway WP${{ steps.get_wpid.outputs.wpid }}"
          git push

      - name: Commit and push changes to sandbox-wp-assets
        working-directory: sandbox-wp-assets
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add assets for approved pathway WP${{ steps.get_wpid.outputs.wpid }}"
          git push

      - name: Append Message to PR Description
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
        run: |
          NEW_DESCRIPTION="This PR has been approved and the pathway is being published at WikiPathways. The new WPID is ${{ steps.get_wpid.outputs.wpid }}."
          gh pr edit $PR_NUMBER --add-body "$NEW_DESCRIPTION"

      - name: Close PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.inputs.pr_number }}
        run: |
          gh pr close $PR_NUMBER
