name: PR Label Dispatcher

on:
  pull_request:
    types: [labeled]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch based on label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          label="${{ github.event.label.name }}"
          pr_number="${{ github.event.pull_request.number }}"
          
          case "$label" in
            "approved")
              workflow="3a_approved_pull_request.yml"
              ;;
            "rejected")
              workflow="3b_rejected_pull_request.yml"
              ;;
            "resubmitted")
              workflow="3c_resubmitted_pull_request.yml"
              ;;
            *)
              echo "Label '$label' does not trigger any workflow."
              exit 0
              ;;
          esac
          
          echo "Triggering workflow: $workflow"
          gh workflow run $workflow -f pr_number=$pr_number